# Generated by Django 4.1.4 on 2023-01-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=60)),
                ("question", models.TextField(max_length=400)),
                (
                    "priority",
                    models.TextField(
                        choices=[("L", "Low"), ("M", "Medium"), ("H", "High")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "The Question",
                "verbose_name_plural": "People's Questions",
            },
        ),
    ]
