# Generated by Django 4.1.4 on 2023-01-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_coupon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coupon",
            name="minimun_amount",
            field=models.IntegerField(default=500),
        ),
    ]
